spring.application.name=claims-mvp

spring.datasource.url=jdbc:postgresql://localhost:5432/claims_mvp
spring.datasource.username=claims_user
spring.datasource.password=claims_pass

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
