spring.application.name=claims-mvp
spring.datasource.url=jdbc:postgresql://localhost:5432/claims_mvp
spring.datasource.username=claims_user
spring.datasource.password=claims_pass
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.upload.dir=uploads

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:false}

app.mail.from=${MAIL_FROM:no-reply@claims-mvp.local}